[package]
name = "ina226"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3"
byteorder = { version = "1", default-features = false }
embedded-hal = "0.2"

[dev-dependencies]
approx = "0.5"
embedded-hal-mock = "0.8"
